import type { Metadata } from "next";
import { Icon } from "@/components/icon";
import { Reveal } from "@/components/reveal";
import { CtaBand, Eyebrow, PageHero, SectionHeading } from "@/components/ui";
import { cooperationOptions, partnerCategories } from "@/data/site";

export const metadata: Metadata = { title: "International Cooperation", description: "Partner with STRIDES Pakistan on open-source security education, research and capacity-building." };

export default function CooperationPage() {
  return <>
    <PageHero title="International Cooperation" description="Partnerships with universities, think tanks, international NGOs, donor agencies, foundations, CSR partners and research networks." />
    <section className="section"><div className="shell cooperation-lead"><Reveal><Eyebrow>Donor & NGO engagement</Eyebrow><h2>Transparent cooperation for public-interest strategic studies.</h2><p>STRIDES Pakistan can work with donating NGOs, foundations, universities and development partners to support research, training, dialogue and awareness programs. The emphasis remains on open-source analysis, policy education, resilience, responsible technology use, maritime safety, cyber awareness and non-partisan strategic understanding.</p><div className="badge-row">{["Open source","Non-partisan","Transparent","Educational","Policy-oriented"].map(x=><span key={x}>{x}</span>)}</div></Reveal><Reveal className="scope-card" delay={100}><span>Cooperation scope</span><h3>Possible international partners</h3><p>International think tanks, universities, research centres, policy institutes, peace and security NGOs, maritime organizations, cybersecurity awareness groups, media-literacy organizations, disaster-resilience NGOs, diaspora foundations and corporate social responsibility partners.</p><p>Partnerships can be formalized through MoUs, project agreements, funded research calls, sponsored training programs and joint events.</p></Reveal></div></section>
    <section className="section soft-section"><div className="shell"><Reveal><SectionHeading eyebrow="Partnership possibilities" title="What partners can support" description="Practical, donor-friendly activities that preserve an independent, non-partisan and open-source character." /></Reveal><div className="support-grid">{cooperationOptions.map(([label,title,text],i)=><Reveal className="support-card" delay={(i%3)*60} key={title}><div><span>{String(i+1).padStart(2,"0")}</span><Icon name={i%3===0?"document":i%3===1?"academic":"people"} size={26}/></div><small>{label}</small><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section className="section"><div className="shell"><Reveal><SectionHeading eyebrow="Partner categories" title="Potential cooperation channels" description="A broad network can connect research, education, resilience and responsible innovation." /></Reveal><div className="partners-grid">{partnerCategories.map(([title,text],i)=><Reveal className="partner-card" delay={(i%4)*50} key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
    <section className="section governance-section"><div className="shell governance-grid"><Reveal><Eyebrow light>Governance</Eyebrow><h2>Safeguards for credible cooperation</h2><p>STRIDES Pakistan should adopt clear donor guidelines and publish basic transparency principles.</p></Reveal><Reveal className="safeguards" delay={100}>{["Accept only legal, transparent and ethical funding.","Maintain editorial and research independence.","Use open-source and publicly available information only.","Avoid classified, operational or weapon-related activities.","Provide project reports, outcomes and financial transparency.","Remain non-partisan and focused on education and resilience."].map(item=><div key={item}><span><Icon name="check" size={16}/></span>{item}</div>)}</Reveal></div></section>
    <CtaBand eyebrow="Why support STRIDES?" title="Invest in responsible strategic education." text="Help strengthen youth awareness, policy literacy, digital resilience, maritime safety and evidence-based national security debate." button="Discuss cooperation" />
  </>;
}
